on:
  push:
    tags:
    - 'v*'

name: Create release from tag

jobs:

  pkl:
    name: Pkl
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./.github/workflows/pkl.sh 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

